server:
  port: 8080

# database
spring:
  datasource:
    name: spring-boot-mybatis
    url: jdbc:mysql://192.168.25.201:3306/spring_boot_shiro
    username: root
    password: root9918
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
# mapper映射文件文职
mybatis:
  mapper-locations: classpath:mapping/*.xml
# 分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql